Tests:  [3/6, ???ms]
    - some property [???ms]
    - other property [???ms]
    - [PENDING] pending property
        Reason: This test is supposed to be ignored.
    - [FAILED] some failing property [???ms]
        Reason: 9 did not equal 4 (at ???/fail_report/Main.enso:22:13-32).
    - something OK [???ms]
    - [FAILED] dataflow error [???ms]
        Reason: An unexpected dataflow error ((Illegal_Argument.Error 'some error' Nothing)) has been matched (at ???/fail_report/Main.enso:28:9-74).
        at <enso> Error.throw(Internal)
        at <enso> Main.spec<arg-0>(???/fail_report/Main.enso:28:9-57)
        ???
        at <enso> Main.main(???/fail_report/Main.enso:33:8-31)
    - [FAILED] panic [???ms]
        Reason: An unexpected panic was thrown: (Illegal_Argument.Error 'some error' Nothing)
        at <enso> Panic.throw(Internal)
        at <enso> Main.spec<arg-1>(???/fail_report/Main.enso:31:9-57)
        ???
        at <enso> Main.main(???/fail_report/Main.enso:33:8-31)
3 tests succeeded.
3 tests failed.
1 tests skipped.
